res:
    - name: awesomeFace
      path: awesomeface.png
    - name: container
      path: container.jpg
    - name: fireball
      path: fireball.png
prefabs:
    - name: fireball
      components:
        - name: spriteComp
          textureName: awesomeFace
        - name: RigidBody
          type: RigidBodyComponent
        - name: colliderComp
          type: ColliderComponent
