---
res:
  - name: awesomeFace
    path: awesomeface.png
  - name: container
    path: container.jpg
  - name: fireball
    path: fireball.png
  - name: simonIdle
    path: simonIdle.png
  - name: bat
    path: bat.png
  - name: skeleton
    path: skeleton.png
  - name: BouncyProjectile
    path: BouncyProjectile.lua
player:
  - name: simon
    hp: 10
    sprite:
      name: playerSprite
      textureName: simonIdle
    projectileSpawner:
      name: playerProjectileSpawner
      spawnRateMod: 1
      speedMod: 20
      damageMod: 1
      areaMod: 1
      durationMod: 1
      amountMod: 1
      playerProjectiles:
        - name: fireball
          type: projectile
          textureName: fireball
          speed: 20.0
          damage: 1
          duration: 2
          hp: 2
          scale: 0.75
          baseSpawnRate: 0.05
enemySpawner:
  name: enemySpawner
  spawnRateMod: 1
  speedMod: 1
  damageMod: 1
  HPMod: 1
  enemies:
    - name: skeleton
      type: basic
      textureName: skeleton
      speed: 100
      damage: 1
      HP: 2
      baseSpawnRate: 1
      scale: 2
    - name: bat
      type: basic
      textureName: skeleton
      speed: 150
      damage: 1
      HP: 1
      baseSpawnRate: 1
      scale: 2
